use_frameworks!
ENV['SWIFT_VERSION'] = '4'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
supports_swift_versions '>= 4.0'

target 'Logsene_Example' do
  pod 'Logsene', :path => '../', :swift_version => '4.0'
  pod 'CocoaLumberjack/Swift'

  target 'Logsene_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
