source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Logsene_Example' do
  pod 'Logsene', :path => '../'
  pod 'CocoaLumberjack/Swift', '~> 3.1.0'
end

target 'Logsene_Tests' do
  pod 'Logsene', :path => '../'

  pod 'Quick', '~> 1.1.0'
  pod 'Nimble', '~> 6.0.1'
end
